apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-service
  name: kafka-service
  namespace: cmt-solution
spec:
  ports:
  - name: "9092"
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    service: kafka-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
