apiVersion: v1
kind: Service
metadata:
  labels:
    service: mail-service
  name: mail-service
  namespace: cmt-solution
spec:
  ports:
  - name: "1025"
    port: 1025
    protocol: TCP
    targetPort: 1025
  - name: "8025"
    port: 8025
    protocol: TCP
    targetPort: 8025
  selector:
    service: mail-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
