server:
  port: 8091
  servlet:
    context-path: /api/v1

spring:
  application:
    name: customer-service

  data:
    mongodb:
      database: customer
      username: seif
      password: seif
      host: 192.168.43.10
      port: 27017
      authentication-database: admin

management:
  metrics:
    tags:
      application: customer-service


