apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb-service
  name: mongodb-service
  namespace: cmt-solution
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    service: mongodb-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
