apiVersion: v1
kind: Service
metadata:
  labels:
    service: zipkin-service
  name: zipkin-service
  namespace: cmt-solution
spec:
  ports:
  - name: "9411"
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    service: zipkin-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
