apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres-service
  name: postgres-service
  namespace: cmt-solution
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    service: postgres-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
