apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis-service
  name: redis-service
  namespace: cmt-solution
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    service: redis-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
