apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
  namespace: cmt-solution
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "2181"
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    service: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
